alias vvv="bash /home/manuj/Bin/VVV-1.4.0-x86_64/vvv-start.sh"
alias cmap="bash /home/manuj/Bin/CMapTools/bin/CmapTools"
alias combine-pdf="gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dAutoRotatePages=/None -sOutputFile=Slides.pdf  *.pdf"
alias combine-png="convert *.png output.pdf"
alias eject-sdb="udisksctl power-off -b /dev/sdb"
alias hugo-server-start="hugo server --disableFastRender"
alias split-text="split --elide-empty-files --suffix-length=3 --numeric-suffixes=1 --line-bytes=10K"
alias kill-vlc="killall -s 9 vlc.bin"
alias backup-laptop-a="rsync --delete --progress --exclude-from=/home/manuj/Backups/RSYNC_EXCLUDE/rsync-homedir-local.txt -vahi /home/manuj/ /media/veracrypt1/SYSTEM_BACKUP/"
alias backup-laptop-b="rsync --delete --progress --exclude-from=/home/manuj/Backups/RSYNC_EXCLUDE/rsync-homedir-local.txt -vahi /home/manuj/ /media/manuj/SYSTEM_B/SYSTEM_BACKUP"
alias backup-laptop-c="rsync --delete --progress -vahi /home/manuj/ /media/veracrypt1/DATA_BACKUP/"
alias backup-backup="rsync --delete --progress -vahi /media/manuj/BACKUP_01_A/ /media/manuj/BACKUP_01_B/"
alias backup-tutorials="rsync --delete --progress -vahi /media/manuj/LEARNING/ /media/manuj/TutsBackup/BACKUP/"
alias backup-queue="rsync --delete --progress -vahi /media/manuj/QUEUE/QUEUE/ /media/manuj/Q_BACKUP/QUEUE_BACKUP/"
