
[greenclip]
  blacklisted_applications = []
  enable_image_support = true
  history_file = "~/.cache/greenclip.history"
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 50
  max_selection_size_bytes = 0
  static_history = ["conda create --name myenv", "conda create --name myclone --clone myenv", "conda remove --name myenv --all", "Positively, Manuj"]
  trim_space_from_selection = false
  use_primary_selection_as_input = false
