#!/home/manuj/anaconda3/bin/python3

from PIL import Image
import glob
import os
from tqdm import tqdm

allPdfFiles = glob.glob("*.jpg")

print("Converting .jpg to .pdf:")

for filename in tqdm(allPdfFiles):
    image = Image.open(filename)
    new_name = filename[:-4] + ".pdf"
    image.save(new_name, "PDF", resolution = 100.0)
    os.remove(filename)
