#!/usr/bin/bash

rsync --delete --progress --exclude-from=$HOME/Backups/RSYNC_EXCLUDE/rsync-homedir-local.txt -vahi $HOME/ /media/manuj/SYSTEM_B/SYSTEM_BACKUP

date | xargs echo > ~/Bin/logs/laptop-backup-b.txt