#!/usr/bin/bash

rsync --delete --progress --exclude-from=/home/manuj/Backups/RSYNC_EXCLUDE/rsync-homedir-local.txt -vahi /home/manuj/ /media/veracrypt1/SYSTEM_BACKUP/

date | xargs echo > ~/Bin/logs/laptop-backup-a.txt