#!/usr/bin/bash

rsync --delete --progress --exclude-from=$HOME/Backups/RSYNC_EXCLUDE/rsync-homedir-local.txt -vahi $HOME/ /media/veracrypt1/SYSTEM_BACKUP/

date | xargs echo > ~/Bin/logs/laptop-backup-a.txt