#!/usr/bin/bash
GREEN='\033[0;32m'
NC='\033[0m' # No Color

TOTAL_SECONDS=$(find . -maxdepth 1 -iname '*.m*' -exec ffprobe -v quiet -of csv=p=0 -show_entries format=duration {} \; | paste -sd+ -| bc)

echo -e "${GREEN}Real Time:${NC}"
echo $TOTAL_SECONDS | awk '{printf("%d:%02d:%02d:%02d\n",($1/60/60/24),($1/60/60%24),($1/60%60),($1%60))}'

echo -e "${GREEN}1.5x:${NC}"
echo $TOTAL_SECONDS | awk '{print $1/1.5}' | awk '{printf("%d:%02d:%02d:%02d\n",($1/60/60/24),($1/60/60%24),($1/60%60),($1%60))}'

