#!/usr/bin/bash

split_duration=${1:-300}

for i in *.m*
	do i="${i%}" mkvmerge -o "SPLIT/$i" "$i" --split duration:"${split_duration}s"
done

for filename in SPLIT/*
do
	name=$(basename -- "$filename")
	name="${name%.*}"
	mv "$filename" "SPLIT/${name}_SPLIT_$(($split_duration/60)).mkv"
done
