#!/usr/bin/bash
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${GREEN}Update Repositories...${NC}"
sudo apt update -y

echo -e "${GREEN}Upgrade Software...${NC}"
sudo apt upgrade -y
flatpak update -y

DAY_OF_WEEK=$(date +%u)

# 1 is Monday
if [ $DAY_OF_WEEK -eq 1 ]
then
    echo -e "${GREEN}Clean Cache...${NC}"

    sudo apt autoremove -y
    sudo apt clean -y
    
    flatpak uninstall --unused -y

    find ~ -type f -iname ".DS_Store" -delete
    find ~ -type d -iname ".ipynb_checkpoints" -prune -exec rm -rf {} \;
fi

hdd-size

date | xargs echo > /home/manuj/Bin/logs/system-update.txt
