#!/usr/bin/bash
GREEN='\033[0;32m'
NC='\033[0m' # No Color

LARGEST=$(for i in *.m*
	do ffmpeg -i "$i" 2>&1 | grep -oP "(?<=Duration: ).*(?=, start.*)"
done | sort -r | head -n 1)

LARGEST_SECONDS=$(echo $LARGEST | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')

if [ ${LARGEST_SECONDS%.*} -gt 600 ]
then
	echo -e "${GREEN}Long video found: $LARGEST Splitting...${NC}"
	video-split-5
	echo -e "${GREEN}Long video found: $LARGEST. Finished Splitting.${NC}"
else
	echo "Nothing to split...exiting."
fi
