window:
  opacity: 0.9

# family: SauceCodePro Nerd Font size 12
# family: RobotoMono Nerd Font size 12.5
font:
  normal:
    family: RobotoMono Nerd Font
    style: Regular

  bold:
    family: RobotoMono Nerd Font
    style: Bold

  italic:
    family: RobotoMono Nerd Font
    style: Italic

  bold_italic:
    family: RobotoMono Nerd Font
    style: Bold Italic

  size: 9  #13 font size will cause an empty line to appear below nvim for this font

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

colors:
  name: Monokai (dark)
  author: Chris Kempson
  primary:
    background: "#272822"
    foreground: "#f8f8f2"
  cursor:
    text: "#272822"
    cursor: "#f8f8f2"
  normal:
    black: "#272822"
    red: "#f92672"
    green: "#a6e22e"
    yellow: "#f4bf75"
    blue: "#66d9ef"
    magenta: "#ae81ff"
    cyan: "#a1efe4"
    white: "#f8f8f2"
  bright:
    black: "#75715e"
    red: "#f92672"
    green: "#a6e22e"
    yellow: "#f4bf75"
    blue: "#66d9ef"
    magenta: "#ae81ff"
    cyan: "#a1efe4"
    white: "#f9f8f5"
