window:
  opacity: 0.95

font:
  normal:
    family: SauceCodePro Nerd Font Mono
    style: Regular

  bold:
    family: SauceCodePro Nerd Font Mono
    style: Bold

  italic:
    family: SauceCodePro Nerd Font Mono
    style: Italic

  bold_italic:
    family: SauceCodePro Nerd Font Mono
    style: Bold Italic

  size: 12  #13 font size will cause an empty line to appear below nvim for this font

colors:
  name: Monokai (dark)
  author: Chris Kempson
  primary:
    background: "#272822"
    foreground: "#f8f8f2"
  cursor:
    text: "#272822"
    cursor: "#f8f8f2"
  normal:
    black: "#272822"
    red: "#f92672"
    green: "#a6e22e"
    yellow: "#f4bf75"
    blue: "#66d9ef"
    magenta: "#ae81ff"
    cyan: "#a1efe4"
    white: "#f8f8f2"
  bright:
    black: "#75715e"
    red: "#f92672"
    green: "#a6e22e"
    yellow: "#f4bf75"
    blue: "#66d9ef"
    magenta: "#ae81ff"
    cyan: "#a1efe4"
    white: "#f9f8f5"
