alias vvv="bash /home/manuj/Bin/VVV-1.4.0-x86_64/vvv-start.sh"
alias cmap="bash /home/manuj/Bin/CMapTools/bin/CmapTools"
alias pdf-combine="gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dAutoRotatePages=/None -sOutputFile=Slides.pdf  *.pdf"
alias png-convert-pdf="convert *.png output.pdf"
alias sdb-eject="udisksctl power-off -b /dev/sdb"
alias hugo-start="hugo server --disableFastRender"
alias text-split="split --elide-empty-files --suffix-length=3 --numeric-suffixes=1 --line-bytes=10K"
alias vlc-kill="killall -s 9 vlc.bin"
alias laptop-backup-a="rsync --delete --progress --exclude-from=/home/manuj/Backups/RSYNC_EXCLUDE/rsync-homedir-local.txt -vahi /home/manuj/ /media/veracrypt1/SYSTEM_BACKUP/"
alias laptop-backup-b="rsync --delete --progress --exclude-from=/home/manuj/Backups/RSYNC_EXCLUDE/rsync-homedir-local.txt -vahi /home/manuj/ /media/manuj/SYSTEM_B/SYSTEM_BACKUP"
alias laptop-backup-full="rsync --delete --progress -vahi /home/manuj/ /media/veracrypt1/DATA_BACKUP/"
alias backup-backup="rsync --delete --progress -vahi /media/manuj/BACKUP_01_A/ /media/manuj/BACKUP_01_B/"
alias tutorials-backup="rsync --delete --progress -vahi /media/manuj/LEARNING/ /media/manuj/TutsBackup/BACKUP/"
alias queue-backup="rsync --delete --progress -vahi /media/manuj/QUEUE/QUEUE/ /media/manuj/Q_BACKUP/QUEUE_BACKUP/"
