alias pdf-combine="gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dAutoRotatePages=/None -sOutputFile=Slides.pdf  *.pdf"
alias png-convert-pdf="convert *.png output.pdf"
alias sdb-eject="udisksctl power-off -b /dev/sdb"
alias sda-eject="udisksctl power-off -b /dev/sda"
alias hugo-start="hugo server --disableFastRender"
