#!/bin/sh
""":"
# This block is run by /bin/sh to find and execute xonsh
exec /home/"$USER"/anaconda3/envs/xonsh/bin/xonsh "$0" "$@"
":"""

import sys

if len(sys.argv) > 1:
	audio_to_play = sys.argv[1]

	# Send std out to /dev/null to prevent fflay from creating an extra
	# line on the terminal
	ffplay -loglevel quiet -autoexit -nodisp @(audio_to_play) out>/dev/null
