#!/bin/sh
""":"
# This block is run by /bin/sh to find and execute xonsh
exec /home/"$USER"/anaconda3/envs/xonsh/bin/xonsh "$0" "$@"
":"""

import os
import sys
import argparse
from rich.console import Console

myhome = os.path.expanduser('~')
sys.path.append(f"{myhome}/.local/bin")
from utilities import get_user_selection

console = Console()

def parse_args():
    parser = argparse.ArgumentParser(description="Change audio")
    parser.add_argument('files', nargs='+', help="Files to process")
    return parser.parse_args()

def process_files(args):
    allFiles = args.files

    console.rule(f"[bold cyan]Audio change...", style="cyan")

    process_selection = get_user_selection(["Speed", "Volume"], "What do you want to do?")
    delete_choice = get_user_selection(["No", "Yes"], "Delete original files after processing?")

    if process_selection == "Speed":
        speed_selection = get_user_selection(["0.5", "0.667", "0.7", "0.8", "0.9", "1.5", "1.65", "1.82", "2.0"], "Select speed:")
        if delete_choice == "Yes":
            audio-speed-change -s @(speed_selection) -d @(allFiles)
        elif delete_choice == "No":
            audio-speed-change -s @(speed_selection) @(allFiles)
    elif process_selection == "Volume":
        volume_selection = get_user_selection(["0.5", "2", "3", "4", "5"], "Select volume:")
        if delete_choice == "Yes":
            audio-volume-change -v @(volume_selection) -d @(allFiles)
        elif delete_choice == "No":
            audio-volume-change -v @(volume_selection) @(allFiles)


def main():
    args = parse_args()

    if args.files:
        process_files(args)
    else:
        console.print(f"[red]No file selected...exiting.")
        audio-play ~/.local/bin/oxygen-sound-theme/Oxygen-K3B-Finish-Error.ogg &

if __name__ == "__main__":
    main()
