#!/bin/sh
""":"
# This block is run by /bin/sh to find and execute xonsh
exec /home/"$USER"/anaconda3/envs/xonsh/bin/xonsh "$0" "$@"
":"""

from rich.console import Console

console = Console()

console.rule("[bold cyan]Backing up backup drive....", style="cyan")

console.print(f"[bold cyan]Deleting previous snapshot...")
sudo btrfs subvolume delete /media/$USER/BACKUP_01_B/BACKUP/@previous

console.print(f"[bold cyan]Creating a new read only snapshot...")
sudo btrfs subvolume snapshot -r /media/$USER/BACKUP_01_B/BACKUP/@current/ /media/$USER/BACKUP_01_B/BACKUP/@previous

console.print(f"[bold cyan]Synchronizing...")
rsync -vahiP --delete /media/$USER/BACKUP_01_A/ /media/$USER/BACKUP_01_B/BACKUP/@current/

date > ~/Software/logs/backup-backup.txt
date > /media/$USER/BACKUP_01_B/BACKUP/@current/backup_date.txt

# sudo btrfs filesystem show

console.rule(style="cyan")

audio-play ~/Bin/oxygen-sound-theme/Oxygen-K3B-Finish-Success.ogg &
