#!/home/manuj/anaconda3/envs/util/bin/python3
# Since we are importing python3 from util environment, pyperclip should be installed in util environment too
# pip install pyperclip

import re
import unicodedata

import pyperclip as pc
from playsound import playsound


def slugify(value, allow_unicode=False):
    """
    Taken from https://github.com/django/django/blob/master/django/utils/text.py
    Convert to ASCII if 'allow_unicode' is False. Convert spaces or repeated
    dashes to single dashes. Remove characters that aren't alphanumerics,
    underscores, or hyphens. Convert to lowercase. Also strip leading and
    trailing whitespace, dashes, and underscores.
    """
    value = str(value)
    if allow_unicode:
        value = unicodedata.normalize("NFKC", value)
    else:
        value = (
            unicodedata.normalize("NFKD", value)
            .encode("ascii", "ignore")
            .decode("ascii")
        )
    value = re.sub(r"[^\w\s-]", "", value.lower())
    return re.sub(r"[-\s]+", "-", value).strip("-_")


clipboard_content = pc.paste()

file_name = slugify(clipboard_content[:40].strip())
file_name = f"/home/manuj/Productivity_System/01 TASK CAPTURE BIN/00 COPY TO HDD/{file_name} #todo.md"

# open file
with open(file_name, "a+") as f:
    f.write(clipboard_content + "\n")

playsound("/home/manuj/Bin/oxygen-sound-theme/Oxygen-K3B-Finish-Success.ogg")
