#!/usr/bin/env python

# Since we are importing python3 from util environment, pyperclip should be installed in util environment too
# /home/<username>/anaconda3/envs/util/bin/pip install pyperclip
# Installing pyobjects in utils venv will cause this script to fail. Only install pyobjects in xonsh venv
#!/usr/bin/env conda run -n util python3

import os
import sys
#print(os.environ["CONDA_PREFIX"])
from datetime import datetime
import pyperclip as pc
from py_utilities import get_valid_filename, get_timestamp, play_audio

myhome = os.path.expanduser('~')
sys.path.append(f"{myhome}/Bin")

clipboard_content = pc.paste()

file_name = get_valid_filename(clipboard_content[:35])

if file_name:
    date_time = get_timestamp()
    file_name = f"{myhome}/Productivity_System/01 TASK CAPTURE BIN/00 COPY TO HDD/{file_name}_{date_time}.txt"

    # open file
    with open(file_name, "a+") as f:
        f.write(clipboard_content + "\n")

    play_audio(f"{myhome}/.local/bin/oxygen-sound-theme/Oxygen-K3B-Finish-Success.ogg")

else:
    play_audio(f"{myhome}/.local/bin/oxygen-sound-theme/Oxygen-K3B-Finish-Error.ogg")
