#!/bin/sh
""":"
# This block is run by /bin/sh to find and execute xonsh
exec /home/"$USER"/anaconda3/envs/xonsh/bin/xonsh "$0" "$@"
":"""

clear
greenclip clear
rm /home/manuj/.cache/greenclip.history

audio-play ~/Bin/oxygen-sound-theme/Oxygen-K3B-Finish-Success.ogg &
