#!/usr/bin/env python3

import os
import argparse

def walklevel(some_dir, level=1):
    some_dir = some_dir.rstrip(os.path.sep)
    assert os.path.isdir(some_dir)
    num_sep = some_dir.count(os.path.sep)
    for root, dirs, files in os.walk(some_dir):
        yield root, dirs, files
        num_sep_this = root.count(os.path.sep)
        if num_sep + level <= num_sep_this:
            del dirs[:]

def rename_directories(walk_dir):
	for root, subdirs, files in walklevel(walk_dir):
		for subdir in subdirs:
			if(subdir[0].isdigit() and not subdir[1].isdigit()):
				new_directory_name = "00" + subdir
				source = os.path.join(root, subdir)
				destination = os.path.join(root, new_directory_name)
				os.rename(source, destination)

			if(subdir[0].isdigit() and subdir[1].isdigit()):
				new_directory_name = "0" + subdir
				source = os.path.join(root, subdir)
				destination = os.path.join(root, new_directory_name)
				os.rename(source, destination)

def rename_files(walk_dir):
	i = 1

	for root, subdirs, files in walklevel(walk_dir):		
		subdirs.sort()
		
		for filename in files:
			source = os.path.join(root, filename)

			new_file_name = f"{i:03d}_{filename}"
			destination = os.path.join(root, new_file_name)
			os.rename(source, destination)

		i += 1

def main():
	parser = argparse.ArgumentParser(description="Renames directories and files.")
	parser.add_argument("directory", type=str, help="The directory to process.")
	args = parser.parse_args()

	rename_directories(args.directory)
	rename_files(args.directory)

if __name__ == "__main__":
    main()
