#!/bin/sh
""":"
# This block is run by /bin/sh to find and execute xonsh
exec /home/"$USER"/anaconda3/envs/xonsh/bin/xonsh "$0" "$@"
":"""

import os
import sys

from rich.progress import track
from rich.console import Console

console = Console()

# sys.argv[0] is the name of the script which will always be there
selection = False

if len(sys.argv) > 1: # Arguments passed
	selection = True

if selection:	
	allFiles = sys.argv[2:]
	tag = sys.argv[1]
	allFiles.sort()

	console.rule(f"[bold cyan]Removing tag #{tag}...", style="cyan")

	for file in track(allFiles, description="[bold cyan]Untagging : [/bold cyan]"):
		new_filename = file.replace(f" #{tag}", "")
		new_filename = new_filename.strip()
		os.rename(file, new_filename)
else:
	console.print("No files selected!", style="bold red")
	audio-play ~/.local/bin/oxygen-sound-theme/Oxygen-K3B-Finish-Error.ogg &

console.rule(style="cyan")
