#!/bin/sh
//bin/true; /opt/anaconda3/envs/dotnet/lib/dotnet/dotnet "$0" -- "$@"; __rc=$?; [ -t 1 ] && printf '\033[?1l\033>'; exit $__rc
#:package Spectre.Console@0.57.2
#:property Configuration=Release
#:include utilities.cs

// Move the files ranger has selected into its other pane, with a progress bar.
// Same argument layout as file-copy-ranger: files first, target directory last.

var a = new Args("file-move-ranger", "Move ranger-selected files to a target directory")
    .Rest("files_and_target", min: 2, help: "Files to move, followed by the target directory")
    .Parse(args);

var allFiles = a.Rest.Take(a.Rest.Count - 1).ToList();
var targetDir = a.Rest[^1];

Ui.Begin("Moving files...");

var pymvArgs = new List<string> { "/opt/anaconda3/envs/util/bin/pymv", "-gip" };
pymvArgs.AddRange(allFiles);
pymvArgs.Add(targetDir);

int code = Proc.Run("/opt/anaconda3/envs/util/bin/python", pymvArgs);

if (code != 0) return Ui.NoFiles("Move failed.");

return Ui.Done();
