#!/bin/sh
""":"
# This block is run by /bin/sh to find and execute xonsh
exec /home/"$USER"/anaconda3/envs/xonsh/bin/xonsh "$0" "$@"
":"""

import sys
import os
myhome = os.path.expanduser('~')
sys.path.append(f"{myhome}/.local/bin")

from utilities import get_filename_extension, title_case, set_valid_file_names

# sys.argv[0] is the name of the script which will always be there
if len(sys.argv) > 1:
	allFiles = sys.argv[1:]
	allFiles.sort()

	allFiles = set_valid_file_names(allFiles)

	for file in allFiles:
		file_name, extension = get_filename_extension(file)		

		valid_file_name = title_case(file_name)

		clean_file_name = ""

		# We are dealing with folder if extension is null
		if extension == "":
			clean_file_name = valid_file_name
		else: # We are dealing with files
			clean_file_name = f"{valid_file_name}{extension}"
			clean_file_name = clean_file_name.replace("Pocket ", "")
			clean_file_name = clean_file_name.replace(".Tar", ".tar")

		os.rename(file, clean_file_name)
