#!/bin/sh
""":"
# This block is run by /bin/sh to find and execute xonsh
exec /home/"$USER"/anaconda3/envs/xonsh/bin/xonsh "$0" "$@"
":"""

from rich.progress import track
from rich.console import Console

import sys
import os
myhome = os.path.expanduser('~')
sys.path.append(f"{myhome}/.local/bin")

from utilities import get_filename_extension

console = Console()

# sys.argv[0] is the name of the script which will always be there
selection = False

if len(sys.argv) > 1: # Arguments passed
	selection = True

if selection:	
	allFiles = sys.argv[1:]
	allFiles.sort()

	# Do not add a comment here, as this command is used by other commands
	# and it will break the TUI
	# console.rule(f"[bold cyan]Adding percentage tag...", style="cyan")

	total_files = len(allFiles)
	position = 1
	countdown = total_files

	for file in track(allFiles, description="[bold cyan]Tagging : [/bold cyan]"):
		file_name, extension = get_filename_extension(file)
		new_filename = file_name + \
			f"-{str(countdown).zfill(3)}r" + \
			f"-{str(int((position/total_files)*100)).zfill(3)}p" + \
			extension
		os.rename(file, new_filename)
		position += 1
		countdown -= 1
else:
	console.print("No files selected!", style="bold red")
	audio-play ~/.local/bin/oxygen-sound-theme/Oxygen-K3B-Finish-Error.ogg &

# console.rule(style="cyan")
