#!/bin/sh
""":"
# This block is run by /bin/sh to find and execute xonsh
exec /home/"$USER"/anaconda3/envs/xonsh/bin/xonsh "$0" "$@"
":"""

import sys
import os
myhome = os.path.expanduser('~')
sys.path.append(f"{myhome}/.local/bin")

from utilities import get_filename_extension, get_user_selection

# sys.argv[0] is the name of the script which will always be there
selection = False

if len(sys.argv) > 1:
	selection = True

if selection:
	allFiles = sys.argv[1:]
	allFiles.sort()

	extension_choice = get_user_selection(["mkv", "opus", "mka", "txt"], "Choose new file extension:")

	for file in allFiles:
		file_name, extension = get_filename_extension(file)

		if extension: #Do not add extension to directories
			new_file_name = f"{file_name}.{extension_choice}"
			os.rename(file, new_file_name)
