#!/home/manuj/anaconda3/bin/python3

import os
import glob
from PIL import Image
from tqdm import tqdm

allPdfFiles = glob.glob("*.jpg")

print("Converting .jpg to .pdf:")

for filename in tqdm(allPdfFiles):
    image = Image.open(filename)
    new_name = filename[:-4] + ".pdf"
    image.save(new_name, "PDF", resolution = 100.0)
    # os.remove(filename)

print(u'\u2500' * os.get_terminal_size().columns)

sound-play-success &
