#!/bin/sh
""":"
# This block is run by /bin/sh to find and execute xonsh
exec /home/"$USER"/anaconda3/envs/xonsh/bin/xonsh "$0" "$@"
":"""

import time

from rich.console import Console

console = Console()

console.rule(f"[bold cyan]Laptop Backup Full...", style="cyan")

console.print(f"[bold cyan]Open the container...")
sudo cryptsetup luksOpen /dev/sda luks-laptop-backup-full

console.print(f"[bold cyan]Mount the container...")
sudo mkdir -p /media/$USER/laptop_backup_full

# Change the owner
sudo chown $USER:$USER /media/$USER/laptop_backup_full

# Give some time to /dev/vg-laptop-backup-full/raid1-1 to become available
console.print(f"[bold cyan]Waiting for 5 seconds before mounting...")
time.sleep( 5 )

# mount the directory
if !(sudo mount p"/dev/vg-laptop-backup-full/raid1-1" p"/media/$USER/laptop_backup_full"):
    console.print(f"[bold cyan]Deleting previous snapshot...")
    sudo btrfs subvolume delete /media/$USER/laptop_backup_full/@previous

    console.print(f"[bold cyan]Creating a new read only snapshot...")
    sudo btrfs subvolume snapshot -r /media/$USER/laptop_backup_full/@current /media/$USER/laptop_backup_full/@previous

    console.print(f"[bold cyan]Synchronizing...")
    sudo rsync -vahiP --delete $HOME/ /media/$USER/laptop_backup_full/@current

    date > ~/.local/state/shortcut/laptop-backup-full.txt
    date > /media/$USER/laptop_backup_full/@current/backup_date.txt

    # sudo btrfs filesystem show

    audio-play ~/Bin/oxygen-sound-theme/Oxygen-K3B-Finish-Success.ogg &

else:
    console.print(f"[bold red]Something went wrong. Could not mount.")
    audio-play ~/Bin/oxygen-sound-theme/Oxygen-K3B-Finish-Error.ogg &

console.rule(style="cyan")
