#!/bin/sh
""":"
# This block is run by /bin/sh to find and execute xonsh
exec /home/"$USER"/anaconda3/envs/xonsh/bin/xonsh "$0" "$@"
":"""

import sys
import os
myhome = os.path.expanduser('~')
sys.path.append(f"{myhome}/Bin")

from rich.progress import track
from rich.console import Console
from pypdf import PdfReader, PdfWriter

from utilities import get_mime, get_timestamp

console = Console()
console.rule("[bold cyan]Combining pdf....", style="cyan")

# sys.argv[0] is the name of the script which will always be there
selection = False

if len(sys.argv) > 1:
	selection = True

if selection:
	allFiles = sys.argv[1:]
	allFiles.sort()

	merger = PdfWriter()

	for filename in track(allFiles, description="[bold cyan]Merging : [/bold cyan]"):

		mimestart = get_mime(filename, 1)

		if mimestart != None:			
			if mimestart in ['pdf']:
				merger.append(PdfReader(open(filename, 'rb')))

	output_filename = "combined" + "_" + get_timestamp() + ".pdf"
	merger.write(output_filename)

	audio-play ~/.local/bin/oxygen-sound-theme/Oxygen-K3B-Finish-Success.ogg &

else:
	console.print(f"[bold red]No file selected...exiting.")
	audio-play ~/.local/bin/oxygen-sound-theme/Oxygen-K3B-Finish-Error.ogg &

console.rule(style="cyan")
