#!/bin/sh
""":"
# This block is run by /bin/sh to find and execute xonsh
exec /home/"$USER"/anaconda3/envs/xonsh/bin/xonsh "$0" "$@"
":"""

source ~/.xonshrc

~/anaconda3/envs/xonsh/bin/python ~/Software/ranger-master/ranger.py
