#!/bin/sh
""":"
# This block is run by /bin/sh to find and execute xonsh
exec /home/"$USER"/anaconda3/envs/xonsh/bin/xonsh "$0" "$@"
":"""

from rich.console import Console
console = Console()

console.rule(f"[bold cyan]Backup Sawy Drive...")

console.print(f"[bold cyan]Deleting previous snapshot...")
sudo btrfs subvolume delete /media/$USER/SAWY_01_B/SAWY_BACKUP/@previous

console.print(f"[bold cyan]Creating a new read only snapshot...")
sudo btrfs subvolume snapshot -r /media/$USER/SAWY_01_B/SAWY_BACKUP/@current/ /media/$USER/SAWY_01_B/SAWY_BACKUP/@previous

console.print(f"[bold cyan]Synchronizing...")
rsync -vahiP --delete /media/$USER/SAWY_01_A/SAWY/ /media/$USER/SAWY_01_B/SAWY_BACKUP/@current/

date > ~/.local/state/shortcut/sawy-backup.txt

console.rule(style="cyan")

audio-play ~/Bin/oxygen-sound-theme/Oxygen-K3B-Finish-Success.ogg &
