#!/bin/sh
""":"
# This block is run by /bin/sh to find and execute xonsh
exec /home/"$USER"/anaconda3/envs/xonsh/bin/xonsh "$0" "$@"
":"""

#import datetime

#video-process
viperos-update

# Get today's date
# today = datetime.datetime.now()

# Get the day of the month
# day = today.day

# # Check if it's divisible by 7
# if day % 7 == 0:
#     audiobook-progress

sudo shutdown -h now
